export enum ColourScapes {
  BW = 'B-W',
  HISTOGRAM = 'HISTOGRAM',
  XYZ = 'XYZ',
  LAB = 'LAB',
  CMYK = 'CMYK',
  LABQ = 'LABQ',
  RGB = 'RGB',
  CMC = 'CMC',
  LCH = 'LCH',
  LABS = 'LABS',
  SRGB = 'SRGB',
  YXY = 'YXY',
  FOURIER = 'FOURIER',
  RGB16 = 'RGB16',
  GREY16 = 'GREY16',
  MATRIX = 'MATRIX',
  SCRGB = 'SCRGB',
  HSV = 'HSV',
}
