import {
  AFFINE_INITIAL_AVAL,
  AFFINE_INITIAL_BVAL,
  AFFINE_INITIAL_CVAL,
  AFFINE_INITIAL_DVAL,
  BLUR_SIGMA_MIN_VALUE,
  GAMMA_DEFAULT_VALUE,
  GAMMA_OUT_DEFAULT_VALUE,
  MEDIAN_DEFAULT_VAL,
  SHARPEN_M1_DEFAULT,
  SHARPEN_M2_DEFAULT,
  SHARPEN_SIGMA_MIN_VALUE,
  SHARPEN_X1_DEFAULT,
  SHARPEN_Y2_DEFAULT,
  SHARPEN_Y3_DEFAULT,
  THRESHOLD_DEFAULT_VAL,
  TRANSPARENT_COLOR,
} from '@shared/constants/options.constants';
import { ColourScapes } from '@shared/types/formatTypes/coloursSpace.type';
import { ChannelTypes } from '@shared/types/formats.type';
import { IOptions } from '@shared/types/options.type';
import { LocalStorage } from '@shared/utils/localStorage';

const getStateFromLocalStorage = (): IOptions | undefined => {
  const { options } = LocalStorage.getOptionsData();
  return options;
};
const initialState: IOptions = {
  isOptionsUpdated: true,
  isOptionsReseted: true,
  isExtend: false,
  leftExtend: 0,
  rightExtend: 0,
  topExtend: 0,
  bottomExtend: 0,
  isExtendColor: false,
  extendColor: TRANSPARENT_COLOR,
  isExtract: false,
  leftExtract: 0,
  topExtract: 0,
  widthExtract: 0,
  heightExtract: 0,
  isRotate: false,
  rotate: 0,
  isRotateBg: false,
  rotateBg: TRANSPARENT_COLOR,
  isFlip: false,
  isFlop: false,
  isAffine: false,
  affineA: AFFINE_INITIAL_AVAL,
  affineB: AFFINE_INITIAL_BVAL,
  affineC: AFFINE_INITIAL_CVAL,
  affineD: AFFINE_INITIAL_DVAL,
  isSharpen: false,
  isSharpenDefaults: false,
  isSharpenSigma: false,
  sharpenSigma: SHARPEN_SIGMA_MIN_VALUE,
  isSharpenM1: false,
  sharpenM1: SHARPEN_M1_DEFAULT,
  isSharpenM2: false,
  sharpenM2: SHARPEN_M2_DEFAULT,
  isSharpenX1: false,
  sharpenX1: SHARPEN_X1_DEFAULT,
  isSharpenY2: false,
  sharpenY2: SHARPEN_Y2_DEFAULT,
  isSharpenY3: false,
  sharpenY3: SHARPEN_Y3_DEFAULT,
  isMedian: false,
  isMedianSize: false,
  medianSize: MEDIAN_DEFAULT_VAL,
  isBlur: false,
  isBlurDefaultSettings: false,
  isBlurSigma: false,
  blurSigma: BLUR_SIGMA_MIN_VALUE,
  isFlatten: false,
  isFlattenBg: false,
  flattenBg: TRANSPARENT_COLOR,
  isUnflatten: false,
  isGamma: false,
  isGammaVal: false,
  gammaVal: GAMMA_DEFAULT_VALUE,
  isGammaOut: false,
  gammaOut: GAMMA_OUT_DEFAULT_VALUE,
  isNegate: false,
  isNegateAlpha: false,
  isNormalize: false,
  isNormalizeLower: false,
  normalizeLower: 1,
  isNormalizeUpper: false,
  normalizeUpper: 99,
  isClahe: false,
  isClaheWidth: false,
  claheWidth: 0,
  isClaheHeight: false,
  claheHeight: 0,
  isClaheMaxSlope: false,
  claheMaxSlope: 3,
  isConvolve: false,
  isThreshold: false,
  isThresholdVal: false,
  thresholdVal: THRESHOLD_DEFAULT_VAL,
  isThresholdGreyscale: true,
  isThresholdGrayscale: true,
  isModulate: false,
  isModulateBrightness: false,
  modulateBrightness: 0,
  isModulateSaturation: false,
  modulateSaturation: 0,
  isModulateHue: false,
  modulateHue: 0,
  isModulateLightness: false,
  modulateLightness: 0,
  isTint: false,
  isTintColor: false,
  tintColor: TRANSPARENT_COLOR,
  isGreyscale: false,
  isColourSpace: false,
  colourSpace: ColourScapes.SRGB,
  isChannelManipulation: false,
  isRemoveAlpha: false,
  isEnsureAlpha: false,
  ensureAlphaVal: 1,
  isExtractChannel: false,
  extractChannel: ChannelTypes.NONE,
};

export const initialOptionsState: IOptions = getStateFromLocalStorage() || initialState;
